[package]
name = "identify_the_file"
version = "0.1.0"
authors = ["Ryan Jones-Ward <sciguyryan@gmail.com>"]
edition = "2021"
license = "LGPL-2.1-only"
description = "A testing terminal for Redox"
repository = "https://github.com/sciguyryan/Redox"
homepage = "https://github.com/sciguyryan/Redox"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
lazy_static = "1.5.0"
rayon = "1.10.0"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.121"
uuid = { version = "1.10.0", features = ["serde", "v7"] }
walkdir = "2.5.0"